export const types = {
    FETCH_PARTNERS: 'FETCH_PARTNERS',
    FETCH_PARTNER: 'FETCH_PARTNER',
    DELETE_PARTNER: 'DELETE_PARTNER',
    UPDATE_PARTNER: 'UPDATE_PARTNER',
    CREATE_PARTNER: 'CREATE_PARTNER',
    SET_CURRENT_PARTNER: 'SET_CURRENT_PARTNER',
    SET_PARTNER_STATUS: 'SET_PARTNER_STATUS',
    FETCH_PARTNER_SELECTOR: 'FETCH_PARTNER_SELECTOR'
};