export const types = {
    SET_LIGHT_THEME: 'SET_LIGHT_THEME',
    SET_DARK_THEME: 'SET_DARK_THEME',
    HANDLE_MENU: 'HANDLE_MENU',
    HANDLE_FORM: 'HANDLE_FORM',
    SET_LANGUAGE: 'SET_LANGUAGE',
    SET_COOKIES_VISIBILITY: 'SET_COOKIES_VISIBILITY'
};