export const types = {
    FETCH_CHARATERISTICS: 'FETCH_CHARATERISTICS',
    FETCH_CHARATERISTIC: 'FETCH_CHARATERISTIC',
    DELETE_CHARATERISTIC: 'DELETE_CHARATERISTIC',
    UPDATE_CHARATERISTIC: 'UPDATE_CHARATERISTIC',
    CREATE_CHARATERISTIC: 'CREATE_CHARATERISTIC',
    SET_CURRENT_CHARATERISTIC: 'SET_CURRENT_CHARATERISTIC',
};