export const types = {
    FETCH_INSURANCES: 'FETCH_INSURANCES',
    UPDATE_INSURANCE: 'UPDATE_INSURANCE',
    SET_CURRENT_INSURANCE: 'SET_CURRENT_INSURANCE',
    DELETE_INSURANCE: 'DELETE_INSURANCE',
    CREATE_INSURANCE: 'CREATE_INSURANCE'
};