export const types = {
    FETCH_VEHICLES: 'FETCH_VEHICLES',
    FETCH_VEHICLE: 'FETCH_VEHICLE',
    DELETE_VEHICLE: 'DELETE_VEHICLE',
    UPDATE_VEHICLE: 'UPDATE_VEHICLE',
    CREATE_VEHICLE: 'CREATE_VEHICLE',
    SET_CURRENT_VEHICLE: 'SET_CURRENT_VEHICLE',
    FETCH_VEHICLE_SELECTOR: 'FETCH_VEHICLE_SELECTOR',
    FETCH_DISABLED_DATES: 'FETCH_DISABLED_DATES',
    SET_VEHICLE_STATUS: 'SET_VEHICLE_STATUS'
};