export const types = {
    FETCH_CLIENTS: 'FETCH_CLIENTS',
    FETCH_CLIENT: 'FETCH_CLIENT',
    DELETE_CLIENT: 'DELETE_CLIENT',
    UPDATE_CLIENT: 'UPDATE_CLIENT',
    CREATE_CLIENT: 'CREATE_CLIENT',
    SET_CURRENT_CLIENT: 'SET_CURRENT_CLIENT',
    FETCH_CLIENT_SELECTOR: 'FETCH_CLIENT_SELECTOR'
};