export const types = {
    FETCH_COUNCILS: 'FETCH_COUNCILS',
    FETCH_COUNCIL: 'FETCH_COUNCIL',
    DELETE_COUNCIL: 'DELETE_COUNCIL',
    UPDATE_COUNCIL: 'UPDATE_COUNCIL',
    CREATE_COUNCIL: 'CREATE_COUNCIL',
    SET_CURRENT_COUNCIL: 'SET_CURRENT_COUNCIL',
    FETCH_COUNCIL_SELECTOR: 'FETCH_COUNCIL_SELECTOR',
};