export const types = {
    FETCH_CATEGORIES: 'FETCH_CATEGORIES',
    FETCH_CATEGORY: 'FETCH_CATEGORY',
    DELETE_CATEGORY: 'DELETE_CATEGORY',
    UPDATE_CATEGORY: 'UPDATE_CATEGORY',
    CREATE_CATEGORY: 'CREATE_CATEGORY',
    SET_CURRENT_CATEGORY: 'SET_CURRENT_CATEGORY',
    FETCH_CATEGORY_SELECTOR: 'FETCH_CATEGORY_SELECTOR'
};