export const types = {
    FETCH_BLOCK_PERIODS: 'FETCH_BLOCK_PERIODS',
    DELETE_BLOCK_PERIOD: 'DELETE_BLOCK_PERIOD',
    CREATE_BLOCK_PERIOD: 'CREATE_BLOCK_PERIOD',
    FETCH_BLOCK_PERIODS_SELECTOR: 'FETCH_BLOCK_PERIODS_SELECTOR',
};