export const types = {
    FETCH_BLOCK_DATES: 'FETCH_BLOCK_DATES',
    FETCH_BLOCK_DATES_SELECTOR: 'FETCH_BLOCK_DATES_SELECTOR',
    DELETE_BLOCK_DATE: 'DELETE_BLOCK_DATE',
    CREATE_BLOCK_DATE: 'CREATE_BLOCK_DATE',
};