export const types = {
    FETCH_EXTRAS: 'FETCH_EXTRAS',
    FETCH_EXTRA: 'FETCH_EXTRA',
    DELETE_EXTRA: 'DELETE_EXTRA',
    UPDATE_EXTRA: 'UPDATE_EXTRA',
    CREATE_EXTRA: 'CREATE_EXTRA',
    SET_CURRENT_EXTRA: 'SET_CURRENT_EXTRA',
};