export const types = {
    FETCH_CAR_CATEGORIES: 'FETCH_CAR_CATEGORIES',
    FETCH_CAR_CATEGORY: 'FETCH_CAR_CATEGORY',
    DELETE_CAR_CATEGORY: 'DELETE_CAR_CATEGORY',
    UPDATE_CAR_CATEGORY: 'UPDATE_CAR_CATEGORY',
    CREATE_CAR_CATEGORY: 'CREATE_CAR_CATEGORY',
    SET_CURRENT_CAR_CATEGORY: 'SET_CURRENT_CAR_CATEGORY',
    FETCH_CAR_CATEGORY_SELECTOR: 'FETCH_CAR_CATEGORY_SELECTOR',
    SET_CAR_CATEGORY_STATUS: 'SET_CAR_CATEGORY_STATUS',
    FETCH_AVAILABLE_CAR: 'FETCH_AVAILABLE_CAR',
    FETCH_CAR_CATEGORY_REMOTE_SELECTOR: 'FETCH_CAR_CATEGORY_REMOTE_SELECTOR'
};